import { createContext } from "react"

export const CalculatorContext = createContext({
  isLoadingMake: false,
  selectedMake: "",
  selectedModel: "",
  selectedYear: "",
  selectedVariant: "",
  selectedGeneration: "",
  selectedTrim: "",
  classicMakes: [],
  makes: [],
  relatedVehicles: [],
  chartUrl: "",
  parentChartUrl: "",
  description: "",
  setIsLoadingMake: () => null,
  setSelectedYear: () => null,
  setSelectedMake: () => null,
  setSelectedModel: () => null,
  setSelectedVariant: () => null,
  setSelectedGeneration: () => null,
  setSelectedTrim: () => null,
  setChartUrl: () => null,
  setParentChartUrl: () => null,
  setDescription: () => null,
  setClassicMakes: () => null,
  setMakes: () => null,
  setRelatedVehicles: () => null,
  resetForm: () => null,
})
