import { createContext } from "react"

export const CalculatorContext = createContext({
  isLoadingMake: false,
  isLoadingYear: false,
  selectedMake: "",
  selectedModel: "",
  selectedYear: "",
  selectedVariant: "",
  selectedTrim: "",
  startYear: 0,
  endYear: 0,
  classicMakes: [],
  makes: [],
  relatedVehicles: [],
  chartUrl: "",
  parentChartUrl: "",
  description: "",
  marketId: null,
  setIsLoadingMake: () => null,
  setIsLoadingYear: () => null,
  setSelectedYear: () => null,
  setSelectedMake: () => null,
  setSelectedModel: () => null,
  setSelectedVariant: () => null,
  setSelectedTrim: () => null,
  setChartUrl: () => null,
  setParentChartUrl: () => null,
  setDescription: () => null,
  setStartYear: () => null,
  setEndYear: () => null,
  setClassicMakes: () => null,
  setMakes: () => null,
  setRelatedVehicles: () => null,
  setMarketId: () => null,
  fetchMarket: () => Promise.reject(new Error("Not implemented!")),
  resetForm: () => null,
})
